name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 21
          java-distribution: 'temurin'
          maven-version: 3.9.8
      - name: Run KtLint
        run: make lint
      - name: Run tests
        run: make test