name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 21
          java-distribution: 'temurin'
          maven-version: 3.9.8
      - name: Run KtLint
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 21
          java-distribution: 'temurin'
          maven-version: 3.9.8
      - name: Run tests
        run: make test